#!/usr/bin/env bash

set -e -o pipefail
readonly SCRIPT_DIR=$(dirname "$0")
readonly LOG_DIR="/var/log/azure/run-command-handler"
readonly LOG_FILE=handler.log
readonly ARCHITECTURE=$( [[ "$(uname -p)" == "unknown" ]] && echo "$(uname -m)" || echo "$(uname -p)" ) #ternary operator
HANDLER_BIN="run-command-handler"
if [ $ARCHITECTURE == "arm64" ] || [ $ARCHITECTURE == "aarch64" ]; then
     HANDLER_BIN="run-command-handler-arm64";
fi

# in multiconfig case $ConfigExtensionName and $ConfigSequenceNumber should be set by the agent
readonly EXTENSION_NAME=$ConfigExtensionName
readonly SEQNO=$ConfigSequenceNumber

echo "ConfigExtensionName: $EXTENSION_NAME"
echo "ConfigSequenceNumber: $SEQNO"
echo Architecture: $ARCHITECTURE
echo Binary: $HANDLER_BIN

if [ "$#" -ne 1 ]; then
    echo "Incorrect usage."
    echo "Usage: $0 <command>"
    exit 1
fi

# Redirect logs of the handler process
mkdir -p "$LOG_DIR"
exec &> >(tee -ia "$LOG_DIR/$LOG_FILE")

# Start handling the process in the background
bin="$(readlink -f "$SCRIPT_DIR/$HANDLER_BIN")"
cmd="$1"

# For commands other than 'enable', execute the handler process as a child process
commandToExecute="'$bin' '$cmd'"

if [[ "$cmd" == "enable" ]]; then
    # for 'enable' command, double fork
    # to detach from the handler process tree to avoid getting terminated 
    # after the 15-minute extension enabling timeout.
    # & will execute the binary on the background and will not block current shell execution
    commandToExecute="nohup '$bin' '$cmd' &"
fi

### Retry logic to check if RunCommand binary is open for write and execute the command
set +e # disable exit on non-zero return code
retry_attempts=0

set -x
if command -v fuser &>/dev/null; then # check if fuser command is available
    while (( retry_attempts < 10 )); do
        # Use fuser to detect if the run command binary is open for write to help detect potential conflicts like 'text file busy' errors that prevents execution of Run Command binary.
        fuser_output=$(fuser -vw "$bin" 2>&1)
        fuser_status=$?
        
        # Use 10 retries with 3 seconds sleep between retries to allow for any potential conflicts to resolve before executing the Run Command binary.
        if [ $fuser_status -eq 0 ]; then # atleast one process was found which has opened the binary in write mode.
            echo "RunCommand binary $bin is open for write. User(s) with write access:"
            echo "$fuser_output"
            echo "Binary is open for write. Allowing execution via best-effort path after all retries have been exhausted..."
            ((++retry_attempts))
            echo "sleeping for 3 seconds before retry, attempt ${retry_attempts} of 10"
            sleep 3
            continue
        elif [ $fuser_status -eq 1 ]; then
            echo "Binary $bin is not open for write. All good. Proceeding with execution..."         
            break
        else
            echo "Unexpected fuser error with error code $fuser_status while checking if $bin is open for write using fuser command. Proceeding with best-effort execution..."
            break
        fi
    done
else
    echo "INFO: Not an error. fuser command not found. Install 'psmic' package to use fuser for checking if the Run Command binary is open for write to detect potential conflicts like 'text file busy' errors while executing Run Command binary. Proceeding with best-effort execution..."
fi
### End of retry logic

echo "Starting run-command-handler..."
$commandToExecute
echo "run-command-handler finished."
set +x

set -e
